"""SRun campus network automatic authentication package."""
from __future__ import annotations

__version__ = "1.2.0"

from .client import (
    DEFAULT_PORTAL,
    DEFAULT_PROBE_URL,
    PORTAL_MESSAGES,
    SRUN_BASE64_ALPHABET,
    STANDARD_BASE64_ALPHABET,
    SRunClient,
    SRunError,
    _NoRedirect,
    _display_width,
    _pad_string,
    _print_table,
    _sencode,
    _u32,
    _utf16_code_units,
    dm_sign,
    encode_info,
    format_add_time,
    is_dm_success,
    is_no_response_error,
    is_overlimit_error,
    parse_access_context,
    parse_device_manager_list,
    parse_jsonp,
    parse_online_devices,
    response_message,
    xencode,
)
from .config import (
    CONFIG_VERSION,
    delete_config,
    decrypt_secret,
    encrypt_secret,
    get_default_config_path,
    get_machine_identity,
    load_config,
    save_config,
)
from .cli import (
    CredentialsResult,
    build_parser,
    cli_entry,
    handle_config_command,
    load_credentials,
    main,
    print_devices,
    print_status,
)

__all__ = [
    "DEFAULT_PORTAL",
    "DEFAULT_PROBE_URL",
    "PORTAL_MESSAGES",
    "SRUN_BASE64_ALPHABET",
    "STANDARD_BASE64_ALPHABET",
    "SRunClient",
    "SRunError",
    "_NoRedirect",
    "_display_width",
    "_pad_string",
    "_print_table",
    "_sencode",
    "_u32",
    "_utf16_code_units",
    "dm_sign",
    "encode_info",
    "format_add_time",
    "is_dm_success",
    "is_no_response_error",
    "is_overlimit_error",
    "parse_access_context",
    "parse_device_manager_list",
    "parse_jsonp",
    "parse_online_devices",
    "response_message",
    "xencode",
    "CONFIG_VERSION",
    "delete_config",
    "decrypt_secret",
    "encrypt_secret",
    "get_default_config_path",
    "get_machine_identity",
    "load_config",
    "save_config",
    "CredentialsResult",
    "build_parser",
    "cli_entry",
    "handle_config_command",
    "load_credentials",
    "main",
    "print_devices",
    "print_status",
    "__version__",
]
